config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews, only:[ :index, :show, :new, :create, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    validates :topic, allow_nil: true, length: { maximum: 255 }
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

	def index
		@reviews = current_user.reviews
	end

	def show
		@review = Review.find(params[:id])
	end

	def new
		@gkpt = GkptInformationForm.new(current_user)
	end

	def create
		@gkpt_information_form = GkptInformationForm.new(current_user, gkpt_information_form_params)
		if @gkpt_information_form.save
			flash[:success] = "GKPTが作成されました。"
			redirect_to reviews_path
		else
			render 'new'
		end
	end

	def destroy
    @review = Review.find(params[:id])
		@review.destroy
    flash[:success] = 'GKPTを削除しました'
    redirect_to reviews_url
	end

	private

	def review_params
		params.require(:review).permit(:topic)
	end

	def gkpt_information_form_params
		params.require(:gkpt_information_form).permit(:topic)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
        <%= value %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/13a011236f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<div class="container mt-4">
  <h1>GKPT</h1>
  <%= link_to new_review_path, class: "btn btn-primary mb-3" do %>
    <i class="fa-solid fa-plus"></i>
  <% end %>
  <% @reviews.each do |review| %>
    <%= link_to review_path(review) do %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= review.topic %></h5>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container mt-4">
  <div class="card mb-3">
    <div class="card-header">
      <%= Time.now %>
    </div>
    <div class="card-body">
      <%= form_with model: @gkpt, url: reviews_path, local: true do |form| %>
        <div class="mb-3">
          <%= form.label :topic, class: "form-label" %>
          <%= form.text_field :topic, class: "form-control" %>
        </div>
        <%= form.submit "作成する", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <%= link_to "戻る", reviews_path, class: "btn btn-secondary" %>
</div>

app/views/reviews/show.html.erb
<div class="container mt-4">
  <div class="card mb-3">
    <div class="card-header">
      <%= @review.created_at %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @review.topic %></h5>
    </div>
  </div>
  <%= link_to "戻る", reviews_path, class: "btn btn-secondary" %>
  <%= button_to "削除する", review_path(@review), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger mt-3" %>
</div>